### ISSUE TITLE
List the Project(s) that the task lives in as the Result Subtitle

### ISSUE THREAD

**Issue by joeynotjoe** [adriantoine/alfred-asana#3]
Hello! I realize you haven't worked on this in a year, but I found it very interesting, and now I'm wondering how I might be able to list the project(s) that the task is in in the subtitle of the Alfred results? Possibly the assignee as well? 

Thanks for the great workflow either way!

**Comment by adriantoine** [comment]
Hi!

Sounds like an interesting feature, it's true that I haven't worked on this in a year and I am not even using Asana anymore. I can have a look, it doesn't sound too hard to do, although I haven't looked into that for a while.

I would totally accept a PR for that feature. You can have a look at [Alfy's documentation](https://github.com/sindresorhus/alfy).

**Comment by adriantoine** [comment]
Actually I'm doing it right now

**Comment by adriantoine** [comment]
Done
![screen shot 2017-07-30 at 18 18 52](https://user-images.githubusercontent.com/976570/28755483-07f961f4-7554-11e7-8f6b-42df1c18a513.png)

**Comment by adriantoine** [comment]
So if you upgrade the workflow using [alfred-updater](https://github.com/SamVerschueren/alfred-updater) it should work.

**Comment by joeynotjoe** [comment]
Wow, amazing and quick work. It makes my life so much better, I cannot thank you enough!

**Comment by adriantoine** [comment]
Great! No problem! 👍
